### ISSUE TITLE
Can't seem to get full text search working using SOAP

### ISSUE THREAD

**Issue by frdmn** [ewsterrenburg/python-otrs#10] opened 2016-03-21 10:46 UTC
Hello,

i struggle since about 3 months to get the full text search working via SOAP. 

Already tried asking for help in the official otterhub forum, but noone seems to be able to help me here: [OtterHub - OTRS Community | Full text search via SOAP and GenericTicketConnector](http://forums.otterhub.org/viewtopic.php?f=53&t=30785)

Here's what I use at the moment:

``` python
tickets = client.ticket_search(
    ContentSearch = 'OR',
    From = '%' + args['input'] + '%',
    To = '%' + args['input'] + '%',
    Cc = '%' + args['input'] + '%',
    Subject = '%' + args['input'] + '%',
    Body = '%' + args['input'] + '%',
    Title = '%' + args['input'] + '%'
)
```

... based on the example code in the Ticket.pm file in the OTRS source: https://github.com/OTRS/otrs/blob/1e908159a5dbdcfb94cc35d13bf15b04ac3e6a24/Kernel/System/LinkObject/Ticket.pm#L271-L282, but for some reason it always returns an empty array.

However, it works fine when I try a more simple search like:

``` python
tickets = client.ticket_search(
    Title = '%' + args['input'] + '%'
)
```

I want to search like the full text search in the web ui though. Any ideas?

**Comment by ewsterrenburg** [comment] 2016-03-21 13:11
As far as I can see, **ContentSearch = 'OR'**  is being ignored by the OTRS Generic Ticketconnector. 

When I do some testing, the results appear as if only results are given back for which each of the conditions specified is True. This behavior occurs both calling the TicketConnector from Python and when testing the GenericTicket connector directly using SoapUI.

@frdmn could you do some testing if you agree with me that the ticket connector checks for each condition regardless of the value supplied for  **ContentSearch**? If so, we could file a bug report with OTRS itself.

**Comment by frdmn** [comment] 2016-03-21 13:22
@ewsterrenburg I would love to debug/test this with you! I already spent several months trying to get a proper response from the OTRS team, but no-one really could help me out yet.

Let me know when and how you need my help :+1:

**Comment by ewsterrenburg** [comment] 2016-03-21 13:31
Doesn't sound really hopeful, since I suspect the issue is located within OTRS itself...

@frdmn Could you please check if a request of the following nature only returns you the tickets for which the string being searched for (I used "test", use something that is present in your tickets ;)) occurs both in the subject and body of the ticket. If so, I will put it up on the OTRS mailing list

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns="http://www.otrs.org/TicketConnector/">
  <soapenv:Header/>
  <soapenv:Body>
  <TicketSearch>
           <UserLogin>username</UserLogin>
         <Password>password</Password>
  <Body>test</Body>
  <Subject>test</Subject>
  <ContentSearch>OR</ContentSearch>
</TicketSearch>
  </soapenv:Body>
</soapenv:Envelope>
```

**Comment by frdmn** [comment] 2016-03-21 14:02
Not sure if I do this right, but I setup SoapUI, [downloaded the WSDL](https://github.com/OTRS/otrs/blob/master/development/webservices/GenericTicketConnectorSOAP.wsdl), imported it and tried the following request:

``` xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns="http://www.otrs.org/TicketConnector/">
  <soapenv:Header/>
  <soapenv:Body>
    <TicketSearch>
     <UserLogin>jonas.friedmann</UserLogin>
     <Password>[password]</Password>
     <Body>RapidSSL</Body>
     <Subject>RapidSSL</Subject>
     <ContentSearch>OR</ContentSearch>
   </TicketSearch>
 </soapenv:Body>
</soapenv:Envelope>
```

Which returns the following (error) response:

``` xml
<soap:Envelope soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soap:Body>
      <Fault xmlns="http://www.otrs.org/TicketConnector/">
         <faultcode>Server</faultcode>
         <faultstring>Namespace from SOAPAction 'http://www.otrs.org/TicketConnector' does not match namespace from configuration 'http://www.otrs.org/TicketConnector/'</faultstring>
      </Fault>
   </soap:Body>
</soap:Envelope>
```

Did I miss anything?

**Comment by ewsterrenburg** [comment] 2016-03-21 14:06
Don't know, it's working for me. But you could also test it using your python code I guess...

**Comment by frdmn** [comment] 2016-03-21 14:26
Interesting, works for me via `python-otrs` but not via raw SOAP. I'm going to take a look in the Webservice Debugger and try to compare both requests to see the differences. Stay tuned :)

**Comment by frdmn** [comment] 2016-03-21 14:38
Here's the request received from the debugger:
- via `python-otrs` (works fine): http://paste.frd.mn/ocigo
- via SoapUI.app (doesn't work): http://paste.frd.mn/xeguy

Comparison:

``` diff
2,3c2,3
<   'CONTENT_LENGTH' => '422',
<   'CONTENT_TYPE' => 'text/xml;charset=UTF-8',
---
>   'CONTENT_LENGTH' => '388',
>   'CONTENT_TYPE' => 'text/xml;charset=utf-8',
7,8c7,8
<   'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
<   'HTTP_CONNECTION' => 'Keep-Alive',
---
>   'HTTP_ACCEPT_ENCODING' => 'identity',
>   'HTTP_CONNECTION' => 'close',
10,11c10
<   'HTTP_SOAPACTION' => '"http://www.otrs.org/TicketConnector/TicketSearch"',
<   'HTTP_USER_AGENT' => 'Apache-HttpClient/4.1.1 (java 1.5)',
---
>   'HTTP_USER_AGENT' => 'Python-urllib/2.7',
19c18
<   'REMOTE_PORT' => '56885',
---
>   'REMOTE_PORT' => '56379',
30c29,30
<   'SERVER_SOFTWARE' => 'Apache/2.2.16 (Debian)'
---
>   'SERVER_SOFTWARE' => 'Apache/2.2.16 (Debian)',
>   'SSL_TLS_SNI' => 'ticket.intern.company.de'
```

My guess is that the `HTTP_SOAPACTION` makes the request invalid out of SoapUI. I have no clue how that got in there though - I assume because I imported the WSDL?

**Comment by frdmn** [comment] 2016-03-21 16:27
@ewsterrenburg Finally got it working! Apparently the `SOAPACTION` is a SoapUI-specific behaviour(?). I just tried to send the raw HTTP request using Postman and that immediately worked like a charm.

Regarding your actual question: I've picked a ticket which contains a really unique ticket number from a remote ticket system (2016031410000296) only in the subject, but not in the body.

Now I tried a SOAP request like this:

``` xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns="http://www.otrs.org/TicketConnector/">
  <soapenv:Header/>
  <soapenv:Body>
    <TicketSearch>
     <UserLogin>jonas.friedmann</UserLogin>
     <Password>[password]</Password>
     <Body>2016031410000296</Body>
     <Subject>2016031410000296</Subject>
     <ContentSearch>OR</ContentSearch>
   </TicketSearch>
 </soapenv:Body>
</soapenv:Envelope>
```

And this is what I've received:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soap:Body>
        <TicketSearchResponse xmlns="http://www.otrs.org/TicketConnector/" xsi:nil="true" />
    </soap:Body>
</soap:Envelope>
```

Ergo, the response is completely empty even though, it _should_ actually list at least one ticket ID.

To cross check this problem I removed either `<Body>` or `<Subject>`, and it returned the proper ticket ID as expected.

I guess this confirms our assumptions, right?

**Comment by ewsterrenburg** [comment] 2016-03-21 16:53
@frdmn I agree.
Will you report this to the OTRS development team or should I do so?

**Comment by frdmn** [comment] 2016-03-21 16:56
@ewsterrenburg I am not really familiar with mailing lists, so it would be nice if you could submit it. If you have more important stuff to do right now, I can also try to o it :)

**Comment by ewsterrenburg** [comment] 2016-03-21 19:30
Posted it on the [OTRS mailinglist](https://groups.google.com/forum/#!topic/otrs_archive/k-nV7n-ezn4)

**Comment by frdmn** [comment] 2016-03-22 09:18
Thank you! Now let's wait patiently for a response :)

**Comment by ewsterrenburg** [comment] 2016-04-04 13:43
@frdmn 
no reaction on the mailing list. Reported it with the otrs bugtracker:
[http://bugs.otrs.org/show_bug.cgi?id=11981](http://bugs.otrs.org/show_bug.cgi?id=11981)

**Comment by frdmn** [comment] 2016-04-04 14:57
🙂👍

Von meinem iPhone gesendet

**Comment by frennkie** [comment] 2016-04-14 17:45
I have been working on a Python implementation for the OTRS API over the last few days which - I'll have to admit - actually does the same thing as you have done here. But I really did not want to touch that SOAP stuff and am using the REST interface.
i believe I have run into the same issue with my project as you have:

```
In [10]: client.ticket_search(Subject="%worldwide%")
DEBUG:pyotrs.client:{}
DEBUG:pyotrs.client:search found no results
Out[10]: []

In [11]: client.ticket_search(Body="%worldwide%")
DEBUG:pyotrs.client:{u'TicketID': [u'1']}
Out[11]: [u'1']

In [12]: client.ticket_search(Body="%worldwide%",Subject="%worldwide%",ContentSearch="OR")
DEBUG:pyotrs.client:{}
DEBUG:pyotrs.client:search found no results
Out[12]: []
```

The only ticket I have in my system is the initial "Welcome to OTRS" which has "worldwide" in it's body, so the ticket should also be found in my [12] example, right?!

**Comment by ewsterrenburg** [comment] 2016-04-14 17:53
@frennkie 
I agree with you on this one and expect that ticket to be found...
It keeps being quiet on both OTRS mailinglist and Bugtracker though.

Since @frdmn  has similar experiences of proper responses lacking, priority for the dev team seems to be low. Fortunately, I am not using full text searches anyway.

**Comment by frennkie** [comment] 2016-04-14 17:57
@ewsterrenburg I assume you have absolutely no intention on using/switch to REST as you already have a full SOAP implementation, right? I have not yet published my code but am planning to do so (possibly as "PyOTRS"). Any objections from your side?

**Comment by ewsterrenburg** [comment] 2016-04-14 18:03
@frennkie 

No objections at all and neither any intention to use/switch to REST at the moment. 
Generally I like REST better as well, yet there were two reasons have chosen SOAP:
1. Me being totally clueless how to set up the REST service within OTRS 
2. A perfectly fine solution for SOAP was already available created by @JocelynDelalande  which I could extend.

**Comment by frennkie** [comment] 2016-04-14 18:09
@ewsterrenburg I think you got the wrong frennkie there.. I'm @frennkie ;-)
Otherwise I completely understand you.
Setting up the OTRS REST service is actually very easy and done in two minutes. All you need to do is download the example .yml config from the OTRS repo and upload it as a new web service:
https://github.com/OTRS/otrs/tree/master/development/webservices

**Comment by ewsterrenburg** [comment] 2016-04-14 18:17
@frennkie 
ups, so many fren(n)kies in this world...

Ok, that doesn't seem difficult. Nonetheless I was being clueless when I installed OTRS while the SOAP service  worked right away. So, maybe it's possible to switch someday, yet for now SOAP service does it's job perfectly fine :)

**Comment by frdmn** [comment] 2016-04-14 18:31
@frennkie Perhaps you could "+1" the issue in the bug tracker so the OTRS dev team notice the demand of a fix for this problem.

Right now, my [original project](https://github.com/frdmn/alfred-otrs) is kind of abandoned because it depends on a full text search in OTRS :/

I already thought about just scraping the web page instead for now...

**Comment by frennkie** [comment] 2016-04-14 18:36
@frdmn I already posted a follow up in the OTRS tracker to Bug 11981.

**Comment by frdmn** [comment] 2016-04-14 21:06
@frennkie Oh, I saw Robert's comments but didn't realize it's you. Thanks buddy! :+1:

**Comment by ewsterrenburg** [comment] 2016-07-27 17:02
Issue is clear. Is now fixed in OTRS (at least in OTRS5). Will close this issue.

**Closed as completed by ewsterrenburg** 2016-07-27 17:02 UTC

**Comment by frdmn** [comment] 2016-07-27 17:51
👍

**Comment by Filterer** [comment] 2018-04-06 14:12
Hi all,

I know that this issue is closed but I have the same problem when trying to search tickets based on their article fields (subject, body etc). I m having OTRS 6 on ubuntu and I am executing queries with curl in the terminal. OTRS is also configured as an Invoker with REST and I am using the common GenericTicketConnectorREST webservice with the basic ticket and session functions.

For example:
This query works and searches for tickets with a specific title and the ones that belong to the 'Raw' queue.
curl "http://localhost/otrs/nph-genericinterface.pl/Webservice/GenericTicketConnectorREST/Ticket?SessionID=xLHFqyIbO9OUDZypaFGSVDbe3sA0v3NF&Title=some+title&Queues=Raw"

But this one that searches for tickets with a specific subject it doesn't work and returns all the existing tickets on the OTRS server.
curl "http://localhost/otrs/nph-genericinterface.pl/Webservice/GenericTicketConnectorREST/Ticket?SessionID=xLHFqyIbO9OUDZypaFGSVDbe3sA0v3NF&Subject=some+subject"

Same problem exists for the From, To, CC and Body. ContentSearch and FullTextIndex don't make a difference as well. Also AttachmentName doesn't seem to work as well but that is not article related I guess.

Any help will be appreciated.

**Comment by ewsterrenburg** [comment] 2018-04-07 10:57
@Filterer 
Am I correct that you are not experiencing an issue with the python-otrs library, yet with OTRS itself?

If so, could you please try the [OTRS mailing list](https://groups.google.com/forum/#!forum/otrs_archive)  or one of the OTRS related forums for help...
